package com.filesynch.gui;

import com.filesynch.Main;
import com.filesynch.dto.ClientInfoDTO;
import com.filesynch.dto.ClientStatus;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;
import lombok.Setter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

@Getter
@Setter
public class ConnectToServer {
    private JPanel jPanelMain;
    private JTextField jTextFieldIP;
    private JTextField jTextFieldPort;
    private JTextField jTextFieldName;
    private JButton jButtonConnect;
    private JLabel jLabelIP;
    private JLabel jLabelPort;
    private JLabel jLabelName;
    private JLabel jLabelFilesFolder;
    private JTextField jTextFieldFilesFolder;
    private JLabel jLabelSendFrequency;
    private JLabel jLabelAliveFrequency;
    private JTextField jTextFieldAliveFrequency;
    private JTextField jTextFieldSendFrequency;

    public ConnectToServer() {
        jButtonConnect.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String ip = jTextFieldIP.getText();
                String port = jTextFieldPort.getText();
                String name = jTextFieldName.getText();
                String filesFolder = jTextFieldFilesFolder.getText();
                String sendFrequency = jTextFieldSendFrequency.getText();
                String aliveRequestFrequency = jTextFieldAliveFrequency.getText();
                ClientInfoDTO clientInfoDTO = new ClientInfoDTO();
                clientInfoDTO.setName(name);
                clientInfoDTO.setFilesFolder(filesFolder);
                clientInfoDTO.setSendFrequency(Integer.parseInt(sendFrequency));
                clientInfoDTO.setAliveRequestFrequency(Integer.parseInt(aliveRequestFrequency));
                clientInfoDTO.setStatus(ClientStatus.NEW);
                Main.connectToServer(ip, port, clientInfoDTO);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanelMain = new JPanel();
        jPanelMain.setLayout(new GridLayoutManager(7, 2, new Insets(20, 20, 20, 20), -1, -1));
        jPanelMain.setPreferredSize(new Dimension(400, 300));
        jLabelIP = new JLabel();
        jLabelIP.setText("Server IP:");
        jPanelMain.add(jLabelIP, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jTextFieldIP = new JTextField();
        jPanelMain.add(jTextFieldIP, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jLabelPort = new JLabel();
        jLabelPort.setText("Server Port:");
        jPanelMain.add(jLabelPort, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jLabelName = new JLabel();
        jLabelName.setText("Name:");
        jPanelMain.add(jLabelName, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jTextFieldPort = new JTextField();
        jPanelMain.add(jTextFieldPort, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jTextFieldName = new JTextField();
        jPanelMain.add(jTextFieldName, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jButtonConnect = new JButton();
        jButtonConnect.setText("Connect To Server");
        jPanelMain.add(jButtonConnect, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jLabelFilesFolder = new JLabel();
        jLabelFilesFolder.setText("Files Folder on Server:");
        jPanelMain.add(jLabelFilesFolder, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jTextFieldFilesFolder = new JTextField();
        jPanelMain.add(jTextFieldFilesFolder, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jTextFieldSendFrequency = new JTextField();
        jPanelMain.add(jTextFieldSendFrequency, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jTextFieldAliveFrequency = new JTextField();
        jPanelMain.add(jTextFieldAliveFrequency, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        jLabelSendFrequency = new JLabel();
        jLabelSendFrequency.setText("Send Frequency:");
        jPanelMain.add(jLabelSendFrequency, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jLabelAliveFrequency = new JLabel();
        jLabelAliveFrequency.setText("Alive Request Fequency:");
        jPanelMain.add(jLabelAliveFrequency, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanelMain;
    }

}
